<a href="https://colab.research.google.com/github/cenna-alias/test/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy example
import numpy as np
a = np.array([10,20,30])
print(a)
print(type(a))

[10 20 30]
<class 'numpy.ndarray'>

In [ ]:
# pandas
import pandas as pd
data = ['A','B','C','D']
ser = pd.Series(data)
print(ser)
print(type(ser))

0    A
1    B
2    C
3    D
dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
import numpy as np
import pandas as pd
data = np.arange(21,26)
ser = pd.Series(data)
print(ser)

0    21
1    22
2    23
3    24
4    25
dtype: int64

In [ ]:
import pandas as pd
data = {'A':100,'B':200,'C':300}
ser = pd.Series(data)
print(ser)

A    100
B    200
C    300
dtype: int64

In [ ]:
import pandas as pd
data = ['Apple','Orange','Banana']
df = pd.DataFrame(data)
print(df)
print(type(df))

        0
0   Apple
1  Orange
2  Banana
<class 'pandas.core.frame.DataFrame'>

In [ ]:
import numpy as np
import pandas as pd
l1 = np.arange(1, 65)
print(l1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]

In [ ]:
l2 = l1.reshape((8, 8))
print(l2)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]

In [ ]:
import pandas as pd
data = {
    'name': ['Anu', 'Rahul', 'Meera', 'John', 'Arun', 'Rony', 'Asha', 'Vivek', 'Neha', 'Sanjay', 'Nisha', 'David'],

    'course': ['MBA', 'BCA', 'BTech', 'BCom', 'MCA', 'AI', 'BBA', 'MCom', 'BPharm', 'BSW', 'MA Malayalam', 'BA English'],

    'score': [90,46,78,99,78,89,91,98,97,76,100,96],

    'blood_group': ['A+', 'B+', 'O+', 'AB+', 'A-', 'B-', 'O-', 'AB-', 'A+', 'B+', 'O+', 'AB+'],

    'state': ['Kerala', 'Karnataka', 'Tamil Nadu', 'Kerala', 'Karnataka', 'Tamil Nadu', 'Kerala', 'Karnataka', 'Tamil Nadu', 'Kerala', 'Karnataka', 'Tamil Nadu'],

    'city': ['Kochi', 'Bengaluru', 'Chennai', 'Thrissur', 'Mysuru', 'Coimbatore', 'Kozhikode', 'Hubli', 'Madurai', 'Kollam', 'Mangaluru', 'Salem']
}
df = pd.DataFrame(data)
print(df)

      name        course  score blood_group       state        city
0      Anu           MBA     90          A+      Kerala       Kochi
1    Rahul           BCA     46          B+   Karnataka   Bengaluru
2    Meera         BTech     78          O+  Tamil Nadu     Chennai
3     John          BCom     99         AB+      Kerala    Thrissur
4     Arun           MCA     78          A-   Karnataka      Mysuru
5     Rony            AI     89          B-  Tamil Nadu  Coimbatore
6     Asha           BBA     91          O-      Kerala   Kozhikode
7    Vivek          MCom     98         AB-   Karnataka       Hubli
8     Neha        BPharm     97          A+  Tamil Nadu     Madurai
9   Sanjay           BSW     76          B+      Kerala      Kollam
10   Nisha  MA Malayalam    100          O+   Karnataka   Mangaluru
11   David    BA English     96         AB+  Tamil Nadu       Salem

In [ ]:
df.shape

(12, 6)

In [ ]:
df.size

72

In [ ]:
df.head()

    name course  score blood_group       state       city
0    Anu    MBA     90          A+      Kerala      Kochi
1  Rahul    BCA     46          B+   Karnataka  Bengaluru
2  Meera  BTech     78          O+  Tamil Nadu    Chennai
3   John   BCom     99         AB+      Kerala   Thrissur
4   Arun    MCA     78          A-   Karnataka     Mysuru

In [ ]:
df.tail()

      name        course  score blood_group       state       city
7    Vivek          MCom     98         AB-   Karnataka      Hubli
8     Neha        BPharm     97          A+  Tamil Nadu    Madurai
9   Sanjay           BSW     76          B+      Kerala     Kollam
10   Nisha  MA Malayalam    100          O+   Karnataka  Mangaluru
11   David    BA English     96         AB+  Tamil Nadu      Salem

In [ ]:
df.columns

Index(['name', 'course', 'score', 'blood_group', 'state', 'city'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         12 non-null     object
 1   course       12 non-null     object
 2   score        12 non-null     int64
 3   blood_group  12 non-null     object
 4   state        12 non-null     object
 5   city         12 non-null     object
dtypes: int64(1), object(5)
memory usage: 708.0+ bytes

In [ ]:
df.describe()

            score
count   12.000000
mean    86.500000
std     15.388898
min     46.000000
25%     78.000000
50%     90.500000
75%     97.250000
max    100.000000